#
# GMT 6.5.0 Defaults file
#
# FONT Parameters
#
FONT_ANNOT_PRIMARY             = 7p,Helvetica,black
FONT_LABEL                     = 8p,Helvetica,black
FONT_TITLE                     = 9p,Helvetica-Bold,black
#
# GMT Miscellaneous Parameters
#
GMT_GRAPHICS_DPU               = 600i
#
# MAP Parameters
#
MAP_ANNOT_OFFSET_PRIMARY       = 2p
MAP_ANNOT_OFFSET_SECONDARY     = 2p
MAP_FRAME_PEN                  = 0.6p,black
MAP_FRAME_TYPE                 = plain
MAP_GRID_PEN_PRIMARY           = default,white
MAP_TICK_LENGTH_PRIMARY        = 2p/1p
#
# PostScript Parameters
#
PS_MEDIA                       = a2
